namespace KnowledgeHierarchies
{
    delegate void RecognitionHandler(Boolean arg); // delegate type, for an event.
    [default_interface]
    runtimeclass MainPage : Windows.UI.Xaml.Controls.Page
    {
        MainPage();

        Boolean MyProperty;

    }
}
